nodeLinker: node-modules

npmRegistryServer: "http://***REMOVED***/artifactory/api/npm/npm/"

npmScopes:
  fds:
    npmRegistryServer: "http://***REMOVED***/artifactory/api/npm/npm-fds/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist: ***REMOVED***

yarnPath: .yarn/releases/yarn-2.1.1.cjs
